version: '3.7'
services:
    mysql.wuxt:
        container_name: ${WUXT_MYSQL_CONTAINER:-mysql.wuxt}
        image: mysql:5.7
        volumes:
            - ./_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dev
        networks:
          - default

    wp.wuxt:
        container_name: ${WUXT_WP_CONTAINER:-wp.wuxt}
        image: wordpress:5.2.2-php7.2-apache
        volumes:
          - ./wp-content:/var/www/html/wp-content
        expose:
          - '${WUXT_PORT_BACKEND:-3080}'
        ports:
          - '${WUXT_PORT_BACKEND:-3080}:80'
        environment:
          WORDPRESS_DB_HOST: ${WUXT_MYSQL_CONTAINER:-mysql.wuxt}:3306
          WORDPRESS_DB_NAME: wuxt
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: dev
          WUXT_PORT_BACKEND: ${WUXT_PORT_BACKEND:-3080}
          WORDPRESS_CONFIG_EXTRA: |
            define('WP_SITEURL', 'http://localhost'.(${NGINX_PORT:-80} == 80 ? '' : ${NGINX_PORT:-80} ) );
            define('WP_HOME', 'http://localhost'.(${NGINX_PORT:-80} == 80 ? '' : ${NGINX_PORT:-80} ) );
        networks:
          - default

    front.wuxt:
        container_name: ${WUXT_NUXT_CONTAINER:-front.wuxt}
        image: node:11-slim
        working_dir: '/var/www/app'
        environment:
            - HOST=0.0.0.0
            - WUXT_WP_CONTAINER=${WUXT_WP_CONTAINER:-wp.wuxt}
            - WUXT_PORT_BACKEND=${NGINX_PORT:-80}
        ports:
            - '${WUXT_PORT_FRONTEND-3000}:3000'
        volumes:
            - ./nuxt:/var/www/app
        command: bash -c "yarn install && WUXT_PORT_BACKEND=${NGINX_PORT:-80} yarn dev"
        networks:
          - default

    nginx:
        container_name : nginx
        image: nginx:alpine
        ports:
            - ${NGINX_PORT:-80}:80
        restart: always
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          - default

networks:
    default:
        external:
            name: nginx-proxy
